name: iot_cloud

packages:
  - apps/**
  - packages/**

command:
  version:
    # Only allow versioning to happen on main branch
    branch: main
    # Generates a link to a prefilled GitHub release creation page.
    releaseUrl: true

scripts:
  boot: cd ./packages/iot_cloud_mqtt/docker && docker compose up --build --detach && cd ../../../ && cd ./packages/iot_cloud_server && docker compose up --build --detach && cd ..
  dev: cd ./packages/iot_cloud_mqtt/docker && docker compose up --build --detach && cd ../../../ && cd ./packages/iot_cloud_server && docker compose up --build --detach && dart bin/main.dart --apply-migrations && cd ..
  gen: cd ./packages/iot_cloud_server && serverpod generate && cd ..
  migrate: cd ./packages/iot_cloud_server && serverpod create-migration -f && cd ..
  restart: cd ./packages/iot_cloud_mqtt/docker && docker compose down -v && docker compose up --build --detach && cd ../../../ && cd ./packages/iot_cloud_server && docker compose down -v && docker compose up --build --detach && dart bin/main.dart --apply-migrations && cd ..
  genwatch: cd ./packages/iot_cloud_server && serverpod generate --watch
  format:
    run: melos exec dart format . --fix
    description: Run `dart format` for all packages.
  flutter_clean:
    run: melos exec flutter clean