name: iot_cloud
publish_to: none
environment:
  sdk: ^3.6.0
workspace:
  - packages/iot_cloud_client
  - packages/iot_cloud_mqtt
  - packages/iot_cloud_server
  - packages/iot_cloud_ide
  - packages/iot_cloud_storage_minio
dev_dependencies:
  melos: ^7.0.0-dev.7
