services:
  # Development services
  postgres:
    image: postgres:16.3
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: iot_cloud
      POSTGRES_PASSWORD: "siMyLqTxWUWfhGVQz1FAnGTFRenbRjPF"
    volumes:
      - iot_cloud_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "YXuZgLiJwallacF6yEZ02wkvM__B6pQE"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: postgres:16.3
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: iot_cloud_test
      POSTGRES_PASSWORD: "1YmLulh618ooskfcTi1-4HTSRFzs6TiQ"
    volumes:
      - iot_cloud_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "s-yrpexUtgK_P5ZNRUMn5w9gPCQgR5VU"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  iot_cloud_data:
  iot_cloud_test_data:
